spring.datasource:
    url: jdbc:mysql://47.105.182.72:3306/leyou?useSSL=false
    username: yang
    password: Yzc187600...
    hikari.idle-timeout: 60000
    hikari.maximum-pool-size: 30
    hikari.minimum-idle: 10
server:
    port: 80
#logging.level:
#    com.leyou: debug
# mybatis 别名扫描
mybatis:
  type-aliases-package: com.leyou.pojo

# mapper.xml文件位置,如果没有映射文件，请注释掉
#  mapper-locations: classpath:mappers/*.xml